name: 'platform_dwh'
version: '1.0.0'
config-version: 2

profile: 'platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  platform_dwh:
    ods:
      +materialized: table
      +file_format: parquet
    dds:
      +materialized: table
      +file_format: parquet
    dm:
      +materialized: table
      +file_format: parquet