platform:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      host: "{{ env_var('DBT_TRINO_HOST', 'trino-coordinator') }}"
      port: "{{ env_var('DBT_TRINO_PORT', '8080') | int }}"
      user: "{{ env_var('DBT_TRINO_USER', 'admin') }}"
      database: "{{ env_var('DBT_TRINO_DATABASE', 'iceberg_platform') }}"
      schema: "{{ env_var('DBT_TRINO_SCHEMA', 'ods') }}"
      threads: 4
      http_scheme: http
      cert: false